# Android NDK cross-compilation configuration
# Requires ANDROID_NDK_HOME environment variable to be set

[target.aarch64-linux-android]
ar = "aarch64-linux-android-ar.exe"
linker = "aarch64-linux-android21-clang.cmd"

[target.armv7-linux-androideabi]
ar = "armv7a-linux-androideabi-ar.exe"
linker = "armv7a-linux-androideabi21-clang.cmd"

[target.i686-linux-android]
ar = "i686-linux-android-ar.exe" 
linker = "i686-linux-android21-clang.cmd"

[target.x86_64-linux-android]
ar = "x86_64-linux-android-ar.exe"
linker = "x86_64-linux-android21-clang.cmd"

# Environment variables for native compilation
[env]
CC_aarch64_linux_android = "aarch64-linux-android21-clang.cmd"
CXX_aarch64_linux_android = "aarch64-linux-android21-clang++.cmd"

CC_armv7_linux_androideabi = "armv7a-linux-androideabi21-clang.cmd"
CXX_armv7_linux_androideabi = "armv7a-linux-androideabi21-clang++.cmd"

CC_i686_linux_android = "i686-linux-android21-clang.cmd"
CXX_i686_linux_android = "i686-linux-android21-clang++.cmd"

CC_x86_64_linux_android = "x86_64-linux-android21-clang.cmd"
CXX_x86_64_linux_android = "x86_64-linux-android21-clang++.cmd"
